# This is a basic workflow that is manually triggered

name: api-first-workflow-example

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"

    # API-First Workflow Automation (Pattern) Example
    - uses: actions/checkout@master
    - uses: matt-ball/newman-action@master
      #env:
      #  POSTMAN_API_KEY: ${{ secrets.INSURANCE_API_KEY }}
      #  external_schema_url: https://c7a968e2-f035-4d51-a0b2-794d31eeb4c0.mock.pstmn.io/specs/users.yaml
      with:
        collection: workflow-collections/API-First_Workflow_Pattern_Automations.json
        environment: workflow-collections/Env-Automations-Demo.postman_environment.json
        envVar: '{	"values": [		{			"key": "external-schema-url",			"value": "http://localhost:6845/swagger/v1/swagger.json",			"type": "default",			"enabled": true		}    ]}'
        #envVar: '{"values":[{ "key": "external_schema_url", "value": "https://c7a968e2-f035-4d51-a0b2-794d31eeb4c0.mock.pstmn.io/specs/users.yaml" }]}'
